version: "2.20"
name: football
services:
  db:
    image: postgres:15.5-bullseye
    env_file:
      - ../backend/.env
    ports:
      - "5432:5432" # delete after deployment

  # web:
  #   build: 
  #     context: ../backend/
  #     dockerfile: flask_dockerfile
  #   ports:
  #     - "9001:5000"

  # user:
  #   build:
  #     context: ../frontend/
  #     dockerfile: user_dockerfile
  #   volumes:
  #     - type: bind
  #       source: ../backend/data/
  #       target: /data/
  #   stdin_open: true
  #   tty: true