version: "2.20"
name: football
services:
  db:
    image: postgres:15.5-bullseye
    restart: always
    env_file:
      - ../backend/.env
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432